name: Update Repo Info

on:
  push:
    paths:
      - '.repo.yml'

jobs:
  update-metadata:
    permissions:
      contents: write
    uses: alves-dev/actions/.github/workflows/update-repo-metadata.yml@develop